name: reinmkg
description: "InfoBMKG Remake - A weather application providing weather information for Indonesia with data provided from BMKG."

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  xml2json: ^6.2.7
  numerus: ^2.3.0
  material_symbols_icons: ^4.2874.0
  go_router: ^17.0.0
  get_it: ^9.0.5
  flutter_map: ^8.2.2
  flutter_animate: ^4.5.2
  equatable: ^2.0.7
  countup: ^0.1.4
  froom: ^4.0.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  package_info_plus: ^8.3.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  iconsax: ^0.0.8
  google_fonts: ^6.3.2
  daylight: ^3.1.0
  location: ^8.0.1
  sqflite: ^2.4.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  qweather_icons: ^1.8.0
  flutter_map_geojson:
    git:
      url: https://github.com/StarSkyGeminid/flutter_map_geojson.git
      ref: main
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  apsl_sun_calc:
    git:
      url: https://github.com/StarSkyGeminid/apsl_sun_calc.git
      ref: main
  visibility_detector: ^0.4.0+2
  flutter_map_marker_popup: ^8.1.0
  rename: ^3.1.0
  url_launcher: ^6.3.2

dependency_overrides:
  latlong2: ^0.9.1
  proj4dart: ^2.1.0
  unicode: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  froom_generator: ^4.0.0
  build_runner: ^2.10.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/assets/icon/
    - lib/assets/images/
    - lib/assets/json/

flutter_launcher_icons:
  android: true
  image_path: "lib/assets/images/ic_logo.png"
  adaptive_icon_foreground: "lib/assets/images/ic_logo.png"
  adaptive_icon_background: "#151D2A"

flutter_native_splash:
  color: "#151D2A"
  image: "lib/assets/images/ic_logo.png"
  android: true
  fullscreen: true

  android_12:
    color: "#151D2A"
    image: "lib/assets/images/ic_logo.png"
    icon_background_color: "#151D2A"
